name: test-per-push-pull
run-name: Running tests per push or pull request.
on:
  - push
  - pull_request

jobs:
  run-unit-tests:
    name: Running unit tests.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java for testing.
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Run tests.
        run: mvn -B verify
        timeout-minutes: 2